Added User CRUD
bastien70/dbsaver pull request #13
Opened 2021-08-20 15:43 UTC by bastien70

- Added User CRUD
- New Admin field (BadgeField)
- Updated fixtures to get some ROLE_USER users

2021-08-21 12:08 UTC, jmsche commented on src/Controller/Admin/UserCrudController.php
> +                    ->setLabel('user.action.new');
```suggestion
                return $action->setLabel('user.action.new');
```

2021-08-21 12:08 UTC, jmsche commented on src/Controller/Admin/DashboardController.php
> +        yield MenuItem::linkToCrud('menu.users', 'fas fa-users', User::class);
Missing `setPermission()` to hide it I think.

2021-08-21 12:08 UTC, jmsche commented on src/Controller/Admin/UserCrudController.php
> +            ->setPermission(Action::EDIT, 'ROLE_ADMIN')
Use const from User class?

2021-08-21 12:08 UTC, jmsche commented on src/Controller/Admin/UserCrudController.php
> +        yield BadgeField::new('databasesCount', 'user.field.databases')
Is it possible to drop the getDatabasesCount() method from the User class for this?

2021-08-21 12:08 UTC, jmsche commented on tests/Controller/AbstractControllerTest.php
> +    protected function login(int $userId): void
I'd rather keep this one private, rename `loginAsUser1()` to `loginAsUser()` and create a `loginAsAdmin()`

2021-08-21 12:08 UTC, jmsche commented on src/Entity/User.php
> +    }
See comment in UserCrudController

2021-08-21 12:08 UTC, jmsche commented on src/Controller/Admin/UserCrudController.php
> +                'user.choices.role.admin' => 'ROLE_ADMIN',
Use constants from User class

2021-08-22 13:16 UTC, bastien70 commented on src/Controller/Admin/DashboardController.php
> +        yield MenuItem::linkToCrud('menu.users', 'fas fa-users', User::class);
No because users with only the 'ROLE_USER' role will also have access to this part. However, they will not be able to create, modify, or delete other users. However, they will still be able to modify their own account.

I still hesitate. Either we leave it like that for the moment, or we keep this section only for the ROLE_ADMIN (and in this case we remove the EDIT action because not too much interest here), and we create something elsewhere in a future update to allow the user to change his password.

2021-08-22 19:25 UTC, jmsche requested changes

2021-08-22 19:25 UTC, jmsche commented on fixtures/backup.yaml
> +        database: '@database__user_*'
Please use template to avoid too much code duplication

2021-08-22 19:25 UTC, jmsche commented on fixtures/database.yaml
> +    database__user_{1..5}:
Please use template to avoid too much code duplication

2021-08-22 19:25 UTC, jmsche commented on tests/Controller/AbstractControllerTest.php
> +    public const USER_ROLE_ADMIN = 2;
```suggestion
    public const USER_ROLE_USER = 1;
    public const USER_ROLE_ADMIN = 2;

```

2021-08-23 14:09 UTC, jmsche commented on src/Controller/Admin/DashboardController.php
> +        yield MenuItem::linkToCrud('menu.users', 'fas fa-users', User::class);
If it's only to be able to update your own password (or even your email address) I think it's overkill. A dedicated controller/form would do the trick.

2021-08-23 17:18 UTC, jmsche approved these changes

2021-08-23 17:19 UTC, merged