Added reset password support
bastien70/dbsaver pull request #36
Opened 2021-09-03 16:48 UTC by bastien70

2021-09-04 12:54 UTC, jmsche requested changes

2021-09-04 12:54 UTC, jmsche commented on config/packages/twig.yaml
> +        - "bootstrap_5_layout.html.twig"
```suggestion
        - 'bootstrap_5_layout.html.twig'
```
Using simple quotes to be consistent with the previous line

2021-09-04 12:54 UTC, jmsche commented on migrations/Version20210903135827.php
> +final class Version20210903135827 extends AbstractMigration
```suggestion
final class Version20210903135827 extends AbstractMigration
```

2021-09-04 12:54 UTC, jmsche commented on src/Controller/ResetPasswordController.php
> +        ]);
```suggestion
        return $this->renderForm('reset_password/request.html.twig', [
            'requestForm' => $form,
        ]);
```

2021-09-04 12:54 UTC, jmsche commented on src/Controller/ResetPasswordController.php
> +            ));
Did you test that it was correctly translated?

2021-09-04 12:54 UTC, jmsche commented on src/Controller/ResetPasswordController.php
> +        ]);
```suggestion
        return $this->renderForm('reset_password/reset.html.twig', [
            'resetForm' => $form,
        ]);
```

2021-09-04 12:54 UTC, jmsche commented on src/Controller/ResetPasswordController.php
> +        } catch (ResetPasswordExceptionInterface $e) {
```suggestion
        } catch (ResetPasswordExceptionInterface) {
```

2021-09-04 12:54 UTC, jmsche commented on src/Entity/ResetPasswordRequest.php
> +    }
Isn't this already in the PrimaryKeyTrait?

2021-09-04 12:54 UTC, jmsche commented on src/Form/Model/ResetPasswordRequestModel.php
> +    #[Assert\NotBlank()]
I think adding an Email assert as well would be great

2021-09-04 12:54 UTC, jmsche commented on templates/bundles/EasyAdminBundle/login_layout.html.twig
> +{# @var ea \EasyCorp\Bundle\EasyAdminBundle\Context\AdminContext #}
Why duplicating all this code?

2021-09-04 12:54 UTC, jmsche commented on templates/bundles/EasyAdminBundle/page/login.html.twig
> +{% extends 'bundles/EasyAdminBundle/login_layout.html.twig' %}
Why duplicating all this code?

2021-09-04 12:54 UTC, jmsche commented on templates/reset_password/email.html.twig
> +
I think comments can be removed

2021-09-04 12:54 UTC, jmsche commented on tests/Controller/ResetPasswordControllerTest.php
> +<?php
Maybe more tests can be added?

2021-09-05 15:17 UTC, bastien70 commented on templates/bundles/EasyAdminBundle/login_layout.html.twig
> +{# @var ea \EasyCorp\Bundle\EasyAdminBundle\Context\AdminContext #}
This is a layout that I created myself which will take the main elements of the login page. It serves as a basic template for the other pages (request reset password and reset password), I just have to overload the content block by adding the form. This basic template also contains support for flash messages.

2021-09-05 15:18 UTC, bastien70 commented on templates/bundles/EasyAdminBundle/page/login.html.twig
> +{% extends 'bundles/EasyAdminBundle/login_layout.html.twig' %}
See https://github.com/bastien70/dbsaver/pull/36#discussion_r702439034

2021-09-05 15:26 UTC, bastien70 commented on src/Controller/ResetPasswordController.php
> +            ));
I updated the way to handle this. The translation will be taken into account. Unfortunately, the error message ($ e-> getReason ()) will remain in English no matter what. Possibly we could add a bundle allowing to translate text in any language, but beware of word-for-word translation errors

2021-09-05 15:40 UTC, jmsche commented on templates/bundles/EasyAdminBundle/page/login.html.twig
> +{% extends 'bundles/EasyAdminBundle/login_layout.html.twig' %}
Not needed here I think, see v3.5.8 of EA

2021-09-05 16:04 UTC, bastien70 commented on tests/Controller/ResetPasswordControllerTest.php
> +<?php
I would like to test the reset password itself, but when I manually call the ResetPasswordHelperInterface :: generateResetToken method, I always get the TooManyPasswordRequestsException exception in test mode, which prevents me from going any further. I can't figure out how to get by at this level

2021-09-05 16:13 UTC, bastien70 commented on templates/bundles/EasyAdminBundle/page/login.html.twig
> +{% extends 'bundles/EasyAdminBundle/login_layout.html.twig' %}
It doesn't take into account custom errors if I'm not mistaken. Hence the fact that I added: 

`{% include '@EasyAdmin/flash_messages.html.twig' %}`

2021-09-06 06:00 UTC, jmsche commented on tests/Controller/ResetPasswordControllerTest.php
> +<?php
Maybe change the throttle_limit to a short value for tests (eg. 1 second)

2021-09-06 06:03 UTC, jmsche commented on templates/bundles/EasyAdminBundle/page/login.html.twig
> +{% extends 'bundles/EasyAdminBundle/login_layout.html.twig' %}
The login page itself does not need to be overridden anymore as the login template from EA now contains "forgot password" link.

2021-09-06 06:21 UTC, jmsche commented on templates/bundles/EasyAdminBundle/page/login.html.twig
> +{% extends 'bundles/EasyAdminBundle/login_layout.html.twig' %}
Okay, I've just seen why it's required to override it even with 3.5.8.

2021-09-06 06:24 UTC, jmsche commented on src/Controller/ResetPasswordController.php
> +            ));
I think you could try to catch specific exceptions and then have a specific translated reasons?

2021-09-06 08:28 UTC, jmsche requested changes

2021-09-06 08:28 UTC, jmsche commented on tests/Controller/ResetPasswordControllerTest.php
> +    public function testRequestPasswordReset()
```suggestion
    public function testRequestPasswordReset(): void
```

2021-09-06 08:28 UTC, jmsche commented on tests/Controller/ResetPasswordControllerTest.php
> +    public function testResetPassword()
```suggestion
    public function testResetPassword(): void
```

2021-09-06 08:28 UTC, jmsche commented on translations/messages.en.yaml
> +        flash_error: 'A problem occurred while validating your reset request : %message%'
```suggestion
        flash_error: 'A problem occurred while validating your reset request: %message%.'
```

2021-09-06 08:28 UTC, jmsche commented on translations/messages.fr.yaml
> +        flash_error: 'Un problème est survenu lors de la validation de votre demande de réinitialisation : %message%'
```suggestion
        flash_error: 'Un problème est survenu lors de la validation de votre demande de réinitialisation : %message%.'
```

2021-09-06 09:17 UTC, jmsche requested changes

2021-09-06 09:17 UTC, jmsche commented on src/Controller/ResetPasswordController.php
> +class ResetPasswordController extends AbstractController
```suggestion
final class ResetPasswordController extends AbstractController
```

2021-09-06 09:17 UTC, jmsche commented on tests/Controller/ResetPasswordControllerTest.php
> +class ResetPasswordControllerTest extends AbstractControllerTest
```suggestion
final class ResetPasswordControllerTest extends AbstractControllerTest
```

2021-09-06 09:17 UTC, jmsche commented on tests/Controller/ResetPasswordControllerTest.php
> +     */
Necessary? Should not throw anything

2021-09-06 09:34 UTC, jmsche approved these changes

2021-09-06 09:34 UTC, merged