Added commands to switch storage provider
bastien70/dbsaver pull request #52
Opened 2022-01-25 15:03 UTC by bastien70

See #51 

- Command to manually switch to local storage mode
- Command to manually switch to AWS S3 storage mode
- Storage type initialization at installation

2022-01-29 16:48 UTC, jmsche commented
Why not a single command instead of two?

Also I would not put it in the post install command.

2022-01-31 15:41 UTC, jmsche requested changes

2022-01-31 15:41 UTC, jmsche commented on src/Command/SwitchStorageModeCommand.php
> +    private YamlService $yamlService;
```suggestion
    public const STORAGE_AWS = 'AWS S3';

    private YamlService $yamlService;
```

2022-01-31 15:41 UTC, jmsche commented on src/Command/SwitchStorageModeCommand.php
> +        $editor = $this->editor;
Is this really needed?

2022-01-31 15:41 UTC, jmsche commented on src/Service/YamlService.php
> +    private ?string $absoluteFilePath;
```suggestion
    public const CONFIG_INLINE_LEVEL = 5;

    private ?string $absoluteFilePath;
```

2022-01-31 15:41 UTC, jmsche commented on src/Service/YamlService.php
> +        $this->setAbsoluteFilePath($this->buildFilePath($fileDir, $fileName));
Not sure why you're using the Finder instead of providing the direct path?

2022-02-01 08:09 UTC, jmsche commented
Hi,

I'm not sure this PR (or even how it is currently documented) is the best way to handle an issue: files that are committed to this repository should not be modified.

And, with this PR or the way it's currently documented, project files are modified, implying that the final user can't rebase/upgrade easily.

Maybe one way to fix it correctly would be writing a compiler pass instead?

2022-02-01 08:23 UTC, bastien70 commented
> Hi,
> 
> I'm not sure this PR (or even how it is currently documented) is the best way to handle an issue: files that are committed to this repository should not be modified.
> 
> And, with this PR or the way it's currently documented, project files are modified, implying that the final user can't rebase/upgrade easily.
> 
> Maybe one way to fix it correctly would be writing a compiler pass instead?

Hello,

Yes you are right, during development, inevitably, the configuration file was modified and committed.

But it should be the only feature capable of modifying the configuration file, so afterwards there should be no problems with it. Therefore, the idea could be, just before validating this PR, to put the configuration file back with the default local storage mode.

I've never used compiler pass, are you sure it has to come to this? (given what I said above, since the file shouldn't be changed in future PRs)

2022-02-01 12:23 UTC, jmsche commented
> But it should be the only feature capable of modifying the configuration file, so afterwards there should be no problems with it. Therefore, the idea could be, just before validating this PR, to put the configuration file back with the default local storage mode.

The problem is the file will be modified by the end user, hence blocking their next git pull.

> I've never used compiler pass, are you sure it has to come to this? (given what I said above, since the file shouldn't be changed in future PRs)

Well, I don't see an other way to change the configuration of a bundle without changing a YAML file?

2022-02-01 12:44 UTC, bastien70 commented
Okay I just read the documentation on the compiler pass. So if I understand correctly, it allows us to modify certain configuration values, services, etc.

So we would run it from the kernel?

I have never used this kind of thing. If you know exactly how to do it, could you take over on this PR?

2022-02-01 12:51 UTC, jmsche commented
I'll see what I can do this week

2022-06-15 15:09 UTC, bastien70 commented
I close this PR because the feature will no longer be an idea.

2022-06-15 15:09 UTC, closed without merging