Major changes : User can now configure storage spaces from Dashboard
bastien70/dbsaver pull request #62
Opened 2022-06-15 15:14 UTC by bastien70

BREAKING CHANGES

1. Removed vichuploader + knpgaufrette to use flysystem

2. The user can now configure the storage spaces (adapters) for his backups from the dashboard.
It can currently configure a local adapter, or for S3 (AWS, Scaleway, ...)
For each database, he can choose which adapter to use.

2022-06-15 19:03 UTC, jmsche requested changes
First set of comments

2022-06-15 19:03 UTC, jmsche commented on docs/english.md
> +2. [Manual install](#manual-install)
Please leave "1." for all steps

2022-06-16 06:09 UTC, bastien70 commented on docker-compose.yaml
> +    minio:
It can be useful in the development phase when you don't have an account on S3 (if someone wants to do PR they will have S3 access in dev like that, and it's easier than using their AWS account or Scaleway)

2022-06-16 06:12 UTC, bastien70 commented on Taskfile.yml
> +            - docker-compose -f docker-compose.test.yaml down
Yes. And I don't know why but my "task" command only works if the Taskfile has the extension "yml" and not "yaml". In the doc, this is "yml" extension https://taskfile.dev/

2022-06-16 06:37 UTC, jmsche commented on docker-compose.yaml
> +    minio:
Maybe put it in a .dev.yaml file instead then, but I'd rather only have it in test

2022-06-16 06:37 UTC, jmsche commented on Taskfile.yml
> +            - docker-compose -f docker-compose.test.yaml down
.yaml file handling was added a few months ago, upgrade Task :)

2022-06-16 07:34 UTC, bastien70 commented on Taskfile.yml
> +            - docker-compose -f docker-compose.test.yaml down
Oh good ! I'm also going to put the docker stop back in place of the docker down, it's better

2022-06-16 07:35 UTC, bastien70 commented on docker-compose.yaml
> +    minio:
So the user will have to run the docker-compose.test even in dev?

2022-06-16 07:51 UTC, jmsche commented on docker-compose.yaml
> +    minio:
I don't think there's a real use case for dev, so I'd just drop it

2022-06-16 07:54 UTC, bastien70 commented on docker-compose.yaml
> +    minio:
If a developer wants to do a PR and they want S3 access but they don't have an account with a provider, they would be happy to rely on that. But if we remove it, it will be forced to use the docker-compose.test

2022-06-16 09:12 UTC, jmsche commented on docker-compose.yaml
> +    minio:
Not sure if it's a big deal; also new features should not focus on S3 but on Flysystem in general.

Tests should ensure everything is fine with S3; I really don't see the point of having an S3-like container for dev as it should work like any adapter.

2022-06-18 16:56 UTC, bastien70 commented
I have some gaps with github actions. If someone can take over the PR in order to add minio support in the Github Actions? Because tests will verify the proper functioning of the storage to S3, and it uses minio which will emulate an S3 storage, but I have no idea how to set this up https://min.io/

2022-06-18 23:18 UTC, ToshY commented
@bastien70 If you're talking about the failure in the CI, I don't know if this will help, but looking at the job it calls `http://127.0.0.1:9004/somebucketname/backup
  s/backup_8490.sql`. After a bit of searching I found that you could set the [`use_path_style_endpoint`](https://docs.ceph.com/en/latest/radosgw/s3/php/#creating-a-connection) option to `true` to possibly make it work for this format of endpoint.

2022-06-19 08:27 UTC, bastien70 commented
> @bastien70 If you're talking about the failure in the CI, I don't know if this will help, but looking at the job it calls `http://127.0.0.1:9004/somebucketname/backup s/backup_8490.sql`. After a bit of searching I found that you could set the [`use_path_style_endpoint`](https://docs.ceph.com/en/latest/radosgw/s3/php/#creating-a-connection) option to `true` to possibly make it work for this format of endpoint.

Yes actually it happens during a test that will verify the upload/remove on S3.

Except that it uses minio https://min.io/ to have local S3 support. This works well during testing since we have a docker image running. On the other hand for the CI, minio is not set up, so the test fails. The goal is to be able to include minio in the CI, and that's my problem.

I'm not at all comfortable with continuous integration, so I wouldn't know how to do that, but ideally one should either be able to add minio support to the CI from our config file, or make it so that the tests can launch docker (which implicitly would lead to the creation of minio and therefore the possibility of using it, but I don't know if it's possible or if it's a good practice)

2022-06-27 10:01 UTC, jmsche requested changes

2022-06-27 10:01 UTC, jmsche commented on templates/bundles/EasyAdminBundle/welcome.html.twig
> -    <p>{{ 'dashboard.how_it_works.docs'|trans({ '%docs_link%': 'https://github.com/bastien70/dbsaver' })|raw }}</p>
Changes should be part of an other PR

2022-06-27 11:38 UTC, bastien70 commented on src/Entity/Enum/S3Provider.php
> +    public function getText(): string
I can commit the suggestion, but php-cs-fixer will revert this change

2022-06-27 12:28 UTC, bastien70 commented on templates/bundles/EasyAdminBundle/welcome.html.twig
> -    <p>{{ 'dashboard.how_it_works.docs'|trans({ '%docs_link%': 'https://github.com/bastien70/dbsaver' })|raw }}</p>
Do you want I revert this file and remake it in another PR?

2022-06-27 12:33 UTC, jmsche commented on templates/bundles/EasyAdminBundle/welcome.html.twig
> -    <p>{{ 'dashboard.how_it_works.docs'|trans({ '%docs_link%': 'https://github.com/bastien70/dbsaver' })|raw }}</p>
Yes please

2022-06-27 14:51 UTC, bastien70 commented
It seems good now, no ?

2022-07-02 05:43 UTC, jmsche requested changes

2022-07-02 05:43 UTC, jmsche commented on src/AdapterResolver/LocalAdapterResolver.php
> +//        return new LocalFilesystemAdapter(__DIR__ . sprintf('/../../var/uploads/%s', $this->adapterConfig->getPrefix()));
Should be removed

2022-07-02 05:43 UTC, jmsche commented on src/AdapterResolver/LocalAdapterResolver.php
> +        private readonly string $projectDir
```suggestion
        private readonly string $projectDir,
```

2022-07-02 05:43 UTC, jmsche commented on src/AdapterResolver/S3AdapterResolver.php
> +    public const S3_SCALEWAY_ENDPOINT = 'https://s3.fr-par.scw.cloud';
Is there only one endpoint url available?

2022-07-02 05:43 UTC, jmsche commented on src/Controller/Admin/BackupCrudController.php
> +        private readonly FlysystemHelper $flysystemHelper
```suggestion
        private readonly FlysystemHelper $flysystemHelper,
```

2022-07-02 05:43 UTC, jmsche commented on src/Controller/Admin/DashboardController.php
> +        private readonly EntityManagerInterface $em,
Inject repositories instead

2022-07-02 05:43 UTC, jmsche commented on src/Controller/Admin/DashboardController.php
> +                ->setBadge($this->em->getRepository(LocalAdapter::class)->count([]) ?: null),
Counters should be cached

2022-07-04 08:42 UTC, jmsche requested changes

2022-07-04 08:42 UTC, jmsche commented on src/Controller/Admin/DashboardController.php
> +        ]);
Maybe the caching could happen in the repositories instead? Also, cache should be invalidated when an adapter is removed/added.

2022-07-04 08:51 UTC, jmsche commented
Added my final review I guess.

About CI failure, can you try running minio as a Docker image? Maybe it would work.

2022-07-04 10:42 UTC, bastien70 commented
> Added my final review I guess.
> 
> About CI failure, can you try running minio as a Docker image? Maybe it would work.

I'm not sure what you expect from me.

You would like me to add a command in the CI file that would start the minio docker container present in the docker-compose.yaml, right?

2022-07-04 10:52 UTC, jmsche commented
> You would like me to add a command in the CI file that would start the minio docker container present in the docker-compose.yaml, right?

Either this, or run the minio image directly.

2022-07-04 11:26 UTC, bastien70 commented
> > You would like me to add a command in the CI file that would start the minio docker container present in the docker-compose.yaml, right?
> 
> Either this, or run the minio image directly.

Seems that I can't add these lines in the continuous-integration file :+1: 

Before load fixtures : 

```yaml
      - name: Start minio
      - run: |
          docker-compose -f docker-compose.test.yaml up minio -d
          docker-compose -f docker-compose.test.yaml up createbuckets -d
```

After tests : 

```yaml
      - name: Stop minio
      - run: |
          docker-compose -f docker-compose.test.yaml stop minio
          docker-compose -f docker-compose.test.yaml stop createbuckets
```

(I don't know if this is the kind of thing you were expecting, I'm not very familiar with CI or docker).

When I tried to push, I've the following error : 

```
 ! [remote rejected] issue_58 -> issue_58 (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/continuous-integration.yml` without `workflow` scope)
error: impossible de pousser des références vers 'https://github.com/bastien70/dbsaver.git'
```

2022-07-05 07:44 UTC, ToshY commented
@bastien70 If I didn't know any better, the error makes it seem that the workflow scope isn't enabled for the personal access token being used.

---
![image](https://user-images.githubusercontent.com/31921460/177276329-af487f6a-4532-4928-8db2-518f7a144a95.png)

2022-07-05 07:50 UTC, bastien70 commented
> @bastien70 If I didn't know any better, the error makes it seem that the workflow scope isn't enabled for the personal access token being used.
> 
> ![image](https://user-images.githubusercontent.com/31921460/177276329-af487f6a-4532-4928-8db2-518f7a144a95.png)

Oh okay, it was that, thank you :)

2022-07-05 07:58 UTC, jmsche requested changes

2022-07-05 07:58 UTC, jmsche commented on src/EventSubscriber/S3AdapterSubscriber.php
> +        private readonly CacheInterface $cache
```suggestion
        private readonly CacheInterface $cache,
```

2022-07-05 07:58 UTC, jmsche commented on src/Repository/LocalAdapterRepository.php
> +        return $this->cache->get('local_adapter_count', function (ItemInterface $item) use ($criteria) {
```suggestion
        return $this->cache->get('local_adapter_count', function (ItemInterface $item) use ($criteria): int {
```

2022-07-05 07:58 UTC, jmsche commented on src/Repository/S3AdapterRepository.php
> +        return $this->cache->get('s3_adapter_count', function (ItemInterface $item) use ($criteria) {
```suggestion
        return $this->cache->get('s3_adapter_count', function (ItemInterface $item) use ($criteria): int {
```

2022-07-05 07:58 UTC, jmsche commented on src/Controller/Admin/DashboardController.php
> +                ->setBadge($this->s3AdapterRepository->count([]) ?: null),
```suggestion
                ->setBadge($this->s3AdapterRepository->count([])),
```

2022-07-05 07:58 UTC, jmsche commented on src/Controller/Admin/DashboardController.php
> +                ->setBadge($this->localAdapterRepository->count([]) ?: null),
```suggestion
                ->setBadge($this->localAdapterRepository->count([])),
```

2022-07-05 08:15 UTC, bastien70 commented
A priori, minio starts well.
On the other hand, the tests always give an error which I do not explain. Locally I have no problem.

I will look later

2022-07-26 12:05 UTC, bastien70 commented
Ok I have no idea, I don't understand what is blocking

2022-07-29 12:42 UTC, bastien70 commented
I believe I can fly <3

2022-07-29 12:51 UTC, jmsche requested changes

2022-07-29 12:51 UTC, jmsche commented on .github/workflows/continuous-integration.yml
> +          bin/console app:fixtures:load --env=test
```suggestion
          bin/console app:fixtures:load --env=test
```

2022-07-29 12:51 UTC, jmsche commented on .github/workflows/continuous-integration.yml
> +          docker-compose -f docker-compose.test.yaml up -d createbuckets
You should merge these

2022-07-29 12:51 UTC, jmsche commented on .github/workflows/continuous-integration.yml
> +          docker-compose -f docker-compose.test.yaml stop createbuckets
I don't thing stopping createbuckets is necessary

2022-07-29 12:59 UTC, jmsche requested changes

2022-07-29 12:59 UTC, jmsche commented on .github/workflows/continuous-integration.yml
> +          docker-compose -f docker-compose.test.yaml up -d minio createbuckets
```suggestion
        run: docker-compose -f docker-compose.test.yaml up -d minio createbuckets
```

2022-07-29 12:59 UTC, jmsche commented on .github/workflows/continuous-integration.yml
> +          docker-compose -f docker-compose.test.yaml stop minio
```suggestion
        run: docker-compose -f docker-compose.test.yaml stop minio
```

2022-07-29 13:02 UTC, jmsche approved these changes

2022-07-29 13:03 UTC, merged

2022-07-29 13:03 UTC, jmsche commented
Congrats @bastien70 :)

2022-07-29 13:06 UTC, bastien70 commented
Thank you :)