Added backup options when creating/updating database
bastien70/dbsaver pull request #70
Opened 2022-07-29 14:55 UTC by bastien70

This PR should allow users to set backup options when creating or updating database

2022-07-29 17:22 UTC, jmsche requested changes

2022-07-29 17:22 UTC, jmsche commented on migrations/Version20220729140330.php
> +        $this->addSql('ALTER TABLE `database` ADD reset_auto_increment TINYINT(1) DEFAULT FALSE NOT NULL, ADD add_drop_database TINYINT(1) DEFAULT FALSE NOT NULL, ADD add_drop_table TINYINT(1) DEFAUL
```suggestion
        $this->addSql('ALTER TABLE `database` ADD reset_auto_increment TINYINT(1) DEFAULT FALSE NOT NULL, ADD add_drop_database TINYINT(1) DEFAULT FALSE NOT NULL, ADD add_drop_table TINYINT(1) DEFAULT TRUE NOT NULL, ADD add_drop_trigger TINYINT(1) DEFAULT TRUE NOT NULL, ADD add_locks TINYINT(1) DEFAULT TRUE NOT NULL, ADD complete_insert TINYINT(1) DEFAULT FALSE NOT NULL');
```

2022-07-29 17:22 UTC, jmsche commented on migrations/Version20220729140330.php
> +        $this->addSql('ALTER TABLE `database` DROP reset_auto_increment, DROP add_drop_database, DROP add_drop_table, DROP add_drop_trigger, DROP add_locks, DROP complete_insert');
```suggestion
        $this->addSql('ALTER TABLE `database` DROP reset_auto_increment, DROP add_drop_database, DROP add_drop_table, DROP add_drop_trigger, DROP add_locks, DROP complete_insert');
```

2022-07-29 17:22 UTC, jmsche commented on src/Controller/Admin/DatabaseCrudController.php
> +            yield FormField::addRow();
Is this one needed?

2022-07-29 17:22 UTC, jmsche commented on src/Controller/Admin/DatabaseCrudController.php
> +                ->setColumns(6);
Even if we're not really translating options, these could still be translations

2022-07-29 17:22 UTC, jmsche commented on src/Entity/Database.php
> +    private bool $completeInsert = false;
What about putting them in an embedded $options instead?

2022-07-29 17:22 UTC, jmsche commented on src/Entity/Database.php
> +    private bool $addDropTable = true;
This one is false by default

2022-07-29 17:22 UTC, jmsche commented on src/Service/BackupService.php
> +            $database->getBackupOptions()
```suggestion
            $database->getBackupOptions(),
```

2022-08-01 07:45 UTC, bastien70 commented on src/Controller/Admin/DatabaseCrudController.php
> +            yield FormField::addRow();
Yes options do not need to be on the index. Afterwards, I can override the condition by putting a ->hideOnIndex() on each field if you prefer

2022-08-01 07:52 UTC, bastien70 commented on src/Entity/Database.php
> +    private bool $addDropTable = true;
You had set this option to true by default before managing the options, hence the fact that I set it to true by default. (https://github.com/bastien70/dbsaver/blob/b7a5716a1c6f88288f9b91be0fc2ea90f9abb1e3/src/Service/BackupService.php#L160-L170) Do you still want me to set it to false by default?

2022-08-01 07:53 UTC, jmsche commented on src/Controller/Admin/DatabaseCrudController.php
> +            yield FormField::addRow();
I meant the addRow() in particular

2022-08-01 07:54 UTC, jmsche commented on src/Entity/Database.php
> +    private bool $addDropTable = true;
Let's use the default from the package

2022-08-01 08:09 UTC, bastien70 commented on src/Entity/Database.php
> +    private bool $completeInsert = false;
Why not just a trait ?

2022-08-01 08:18 UTC, bastien70 commented on src/Controller/Admin/DatabaseCrudController.php
> +            yield FormField::addRow();
Oh okay, no I can remove it

2022-08-01 08:26 UTC, jmsche commented on src/Entity/Database.php
> +    private bool $completeInsert = false;
Because it's not at all the role of a trait

2022-08-01 12:17 UTC, jmsche requested changes

2022-08-01 12:17 UTC, jmsche commented on migrations/Version20220801084444.php
> +final class Version20220801084444 extends AbstractMigration
```suggestion
final class Version20220801084444 extends AbstractMigration
```

2022-08-01 12:17 UTC, jmsche commented on src/Entity/Embed/Options.php
> +    public function isResetAutoIncrement(): ?bool
All getters should return bool, not ?bool

2022-08-01 12:29 UTC, jmsche approved these changes

2022-08-15 12:45 UTC, merged