Added backup custom periodicity support
bastien70/dbsaver pull request #73
Opened 2022-08-01 14:31 UTC by bastien70

See #68 

All that remains is to modify the documentation.

2022-08-03 18:42 UTC, jmsche commented on migrations/Version20220801120509.php
> +final class Version20220801120509 extends AbstractMigration
```suggestion
final class Version20220801120509 extends AbstractMigration
```

2022-08-03 18:42 UTC, jmsche commented on src/Entity/Embed/BackupTask.php
> +    #[Assert\Count(min: 1)]
IIRC count is for iterables

2022-08-13 15:30 UTC, jmsche requested changes

2022-08-13 15:30 UTC, jmsche commented on src/Service/BackupService.php
> +    public function getDatabasesToBackup(): array
Can we do this at database level instead?

2022-08-15 08:14 UTC, jmsche approved these changes

2022-08-15 08:14 UTC, jmsche commented on migrations/Version20220801120509.php
> +        $this->addSql('UPDATE `database` SET backup_task_next_iteration = :next_iteration;', ['next_iteration' => (new \DateTime('+1 week'))->format('Y-m-d')]);
Can be done in one query instead

2022-08-15 08:16 UTC, bastien70 commented on migrations/Version20220801120509.php
> +        $this->addSql('UPDATE `database` SET backup_task_next_iteration = :next_iteration;', ['next_iteration' => (new \DateTime('+1 week'))->format('Y-m-d')]);
I found it cleaner to do it like that. Is it really necessary to put it on one line?

2022-08-15 08:21 UTC, jmsche commented on migrations/Version20220801120509.php
> +        $this->addSql('UPDATE `database` SET backup_task_next_iteration = :next_iteration;', ['next_iteration' => (new \DateTime('+1 week'))->format('Y-m-d')]);
One query means it would run faster

2022-08-15 08:22 UTC, bastien70 commented on migrations/Version20220801120509.php
> +        $this->addSql('UPDATE `database` SET backup_task_next_iteration = :next_iteration;', ['next_iteration' => (new \DateTime('+1 week'))->format('Y-m-d')]);
Something like this ?

```php
$this->addSql('ALTER TABLE `database` ADD backup_task_periodicity VARCHAR(255) NOT NULL DEFAULT :periodicity, ADD backup_task_periodicity_number INT NOT NULL DEFAULT 1, ADD backup_task_start_from DATETIME NOT NULL DEFAULT :start_from, ADD backup_task_next_iteration DATETIME NOT NULL DEFAULT :next_iteration', [
            'periodicity' => BackupTaskPeriodicity::WEEK->value,
            'start_from' => (new \DateTime())->format('Y-m-d'),
            'next_iteration' => (new \DateTime('+1 week'))->format('Y-m-d'),
        ]);
```

2022-08-15 08:37 UTC, jmsche commented on migrations/Version20220801120509.php
> +        $this->addSql('UPDATE `database` SET backup_task_next_iteration = :next_iteration;', ['next_iteration' => (new \DateTime('+1 week'))->format('Y-m-d')]);
No, just one update statement after the alter table

2022-08-15 08:44 UTC, bastien70 commented on migrations/Version20220801120509.php
> +        $this->addSql('UPDATE `database` SET backup_task_next_iteration = :next_iteration;', ['next_iteration' => (new \DateTime('+1 week'))->format('Y-m-d')]);
Updated

2022-08-15 08:50 UTC, jmsche reviewed
Docs should be updated I guess

2022-08-15 08:52 UTC, bastien70 commented
> Docs should be updated I guess

Maybe in a new PR after merged the 3 others ? Since there are a lot of changes in the doc between the different PRs, you might as well do it in another one right after

2022-08-15 08:53 UTC, jmsche commented
Sure

2022-08-15 08:53 UTC, jmsche approved these changes

2022-08-15 08:54 UTC, merged