Added backup restoration support
bastien70/dbsaver pull request #76
Opened 2022-09-02 07:37 UTC by bastien70

See #75

2022-09-05 09:02 UTC, jmsche requested changes
First review

2022-09-05 09:02 UTC, jmsche commented on migrations/Version20220902073138.php
> +        $this->addSql('ALTER TABLE `database` CHANGE options_reset_auto_increment options_reset_auto_increment TINYINT(1) NOT NULL, CHANGE options_add_drop_database options_add_drop_database TINYINT(
Why is this happening?

2022-09-12 11:17 UTC, bastien70 commented on composer.json
> +        "ext-mysqli": "*",
that's to say ?

2022-09-12 11:18 UTC, bastien70 commented on migrations/Version20220902073138.php
> +        $this->addSql('ALTER TABLE `database` CHANGE options_reset_auto_increment options_reset_auto_increment TINYINT(1) NOT NULL, CHANGE options_add_drop_database options_add_drop_database TINYINT(
Mmmh no idea, no matter how much I look, the entities have not changed, and nothing should cause that to change

2022-09-12 11:49 UTC, bastien70 commented on composer.json
> +        "ext-mysqli": "*",
Fixed, tell me if it's okay for you

2022-09-12 12:39 UTC, jmsche requested changes

2022-09-12 12:39 UTC, jmsche commented on src/Controller/Admin/BackupCrudController.php
> +        return $this->redirect($context->getReferrer() ?? $this->generateUrl('admin'));
Should redirect to backups list instead

2022-09-12 12:39 UTC, jmsche commented on src/Service/BackupService.php
> +    public function import(Backup $backup): bool
What's the point of returning true? I mean, if it fails, it throws an exception, right?

2022-09-12 13:05 UTC, bastien70 commented on src/Faker/Provider/fixture.sql
> +-- mysqldump-php https://github.com/ifsnop/mysqldump-php
Not particularly, I just replaced the base file with a backup generated by the application, with some tables and data, but it's true that I didn't pay attention to the amount of data inserted. I will modify to keep only a few rows per table maximum

2022-09-12 13:09 UTC, bastien70 commented on src/Service/BackupService.php
> +    public function import(Backup $backup): bool
Yes, if it fails, it throws an exception. But I wasn't sure how to make sure the restoration worked when testing the method (see BackupServiceTest::testImportBackupWithLocalAdapter()), so to check that it was going well, I put an assertTrue rather than an expectNotToPerformAssertions

2022-09-13 07:17 UTC, jmsche commented on src/Service/BackupService.php
> +    public function import(Backup $backup): bool
expectNotToPerformAssertions() would be better I guess

2022-09-13 07:30 UTC, jmsche requested changes

2022-09-13 07:30 UTC, jmsche commented on src/Service/BackupService.php
> +    public function import(Backup $backup): void
```suggestion
    public function import(Backup $backup): void
```

2022-09-13 07:34 UTC, jmsche approved these changes

2022-09-13 07:34 UTC, merged