Template docker
bastien70/dbsaver pull request #87
Opened 2023-05-17 19:24 UTC by TheoMeunier

hi, 

I propose you a complete docker stack for this project that I have set up on a production server and it is very stable. 

I propose you to update it regularly according to the improvement of the project

I hope you will like it and don't need to come to me if you want other functionalities 
;)

2023-05-19 08:24 UTC, bastien70 requested changes
Hey! Thank you for this great contribution! It is indeed something that we would like to have :)

I did a first review. For things a little more technical, I let Jmsche go over it

2023-05-19 08:24 UTC, bastien70 commented on .env.exemple
> +DB_HOST=${APP_SLUG}_database
Not sure if the '_database' suffix is needed here since it can only be that if I'm not mistaken. It would be redundant

2023-05-19 08:24 UTC, bastien70 commented on .gitignore
> +.vscode
This should be part of your global .gitignore, not put in all your projects. Take a look on https://gist.github.com/subfuzion/db7f57fff2fb6998a16c

2023-05-19 08:24 UTC, bastien70 commented on README.md
Maybe add a **"Docker installation guide"** :)

2023-05-19 09:03 UTC, TheoMeunier commented on .env.exemple
> +DB_HOST=${APP_SLUG}_database
the suffix '_database' is necessary because it is the no of the container. you can find them in the docker-compose: https://github.com/TheoMeunier/dbsaver/blob/main/docker-compose.yaml#L37

2023-05-19 09:04 UTC, TheoMeunier commented on README.md
Perfect I will make a doc to see explain the installation of docker on debian and ubuntu

2023-05-19 12:09 UTC, bastien70 commented on README.md
Just to be sure, I'm talking about the installation via docker of the application and not the installation of Docker in general :) (I think you had understood)

You can put that under "Installation with Task" (or that of the maker).

A very simple trick will do, it's just to signal that they can use Docker. Besides, I'm not a Docker pro. Did you set up something in the docker script to initialize the application for the 1st time, or do you have to run "task install" or "make install" before?

2023-05-19 13:45 UTC, TheoMeunier commented on README.md
We can do the installation of the project via "make install" or "task install" or via docker commands. So I will add the installation process via docker simply. 

The implementation of docker was created using my template where we can find all the information for the installation, which I could implement in this project ;)

https://github.com/TheoMeunier/symfony-template

2023-05-19 14:08 UTC, bastien70 commented on README.md
Yes you can add it on the Task file too ;)

Wow, a docker image would be awesome!

I let @jmsche for the end of the review :)

2023-05-22 09:50 UTC, jmsche requested changes

2023-05-22 09:50 UTC, jmsche commented on .env.exemple
> +DB_HOST=${APP_SLUG}_database
Can you rename this to `.env.example`?

2023-05-22 09:50 UTC, jmsche commented on .env.exemple
> +#DATABASE_URL="postgresql://db_user:db_password@127.0.0.1:5432/db_name?serverVersion=13&charset=utf8"
You can remove this line, Postgres is not officially supported by this app.

2023-05-22 09:50 UTC, jmsche commented on .env.exemple
> +#DATABASE_URL="sqlite:///%kernel.project_dir%/var/dbsaver.db"
You can remove this line, sqlite is not officially supported by this app.

2023-05-22 09:50 UTC, jmsche commented on .gitignore
> +.vscode
I can confirm these should not be listed in this file.

2023-05-22 09:50 UTC, jmsche commented on .gitignore
> +/.env
As this app is primarily a Symfony app, the .env file should be versioned.

2023-05-22 09:50 UTC, jmsche commented on Makefile
> +.PHONY: help
I'd rather have this Makefile in a separate PR.

BTW some stuff should be adapted, e.g. phpcbf is not included.

2023-05-22 09:50 UTC, jmsche commented on README.md
> +1. To start the server: `make start` (to stop it: `make stop`)
Should be moved to a separate PR with the Makefile.

2023-05-22 09:50 UTC, jmsche commented on README.md
> +Requires [Docker](https://docs.docker.com/) to be installed.
Also required Docker compose IIUC?

2023-05-22 09:50 UTC, jmsche commented on config/packages/doctrine.yaml
> +                password: '%env(resolve:DB_PASSWORD)%'
Everything could be on the dbal level instead of explicitly defining a default connection.

Also, I'd like to keep the DATABASE_URL environment variable, so every parameter could be resolved in it instead.

2023-05-22 09:50 UTC, jmsche commented on docker/php/local.ini
> +date.timezone=Europe/Berlin
@bastien70 are you okay with this? Maybe set it to Paris instead?

2023-05-22 09:50 UTC, jmsche commented on docker/php/local.ini
> +memory_limit=512M
The app should run with less RAM

2023-05-22 09:50 UTC, jmsche commented on docker/php/Dockerfile
> +FROM php:8.1-fpm
While the app does run with PHP 8.1, [this version will enter security support at the end of the year](https://www.php.net/supported-versions.php), so 8.2 should be used instead.

2023-05-22 09:50 UTC, jmsche commented on docker/php/Dockerfile
> +RUN npm install -g -y yarn
Should be removed.

2023-05-22 09:50 UTC, jmsche commented on docker/php/Dockerfile
> +RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
Should be removed.

2023-05-22 09:50 UTC, jmsche commented on docker/php/Dockerfile
> +    nodejs
Some packages should be removed from this list.

2023-05-22 09:50 UTC, jmsche commented on docker/php/Dockerfile
> +RUN docker-php-ext-install pdo pdo_mysql xsl intl gd
Are xsl & gd really necessary?

2023-05-22 09:50 UTC, jmsche commented on docker/nginx/nginx.conf
> +    # add_header X-Content-Type-Options "nosniff";
To remove

2023-05-22 09:50 UTC, jmsche commented on docker/nginx/nginx.conf
> +    client_max_body_size 308M;
Why?

2023-05-22 09:50 UTC, jmsche commented on docker-compose.yaml
> +            - app_network
I'm not sure I want to include PHP & nginx in the general Docker compose configuration. Maybe this could be moved to a docker-compose.prod.yaml file instead?

2023-05-22 16:52 UTC, TheoMeunier commented on docker-compose.yaml
> +            - app_network
you prefer using symfony cli for dev ?I don't care about that

2023-05-22 16:54 UTC, TheoMeunier commented on docker/php/Dockerfile
> +RUN docker-php-ext-install pdo pdo_mysql xsl intl gd
yes, dependencies is realy neccessay for application, else symfony ask install

2023-05-23 06:56 UTC, bastien70 commented on docker/php/local.ini
> +date.timezone=Europe/Berlin
You're right. It's Europe/Paris

2023-08-15 18:02 UTC, TheoMeunier commented
Hi, 

I'll get back to you to find out what you think of my proposal for a docker application.  
what are the points to improve on my side for my PR to be accepted, I like to work a little for open source and propose a docker version could be really nice 

Isox

2023-08-16 09:02 UTC, jmsche commented
Hi, there are still many points to fix according to latest review. Also, you should rebase the current main branch on yours to allow merging the PR.

2023-08-20 20:08 UTC, TheoMeunier commented
Hello, I have fixed the modifications as well as the things to be fixed. Would there be other things to bring or to modify?

2023-12-30 22:18 UTC, TheoMeunier reviewed
Hello, j'ai mit à jours le projet de Bastien sur mon fork. Ainsi j'ai mis au propre mes modificatios.

2023-12-30 22:18 UTC, TheoMeunier commented on docker/php/Dockerfile
> +RUN npm install -g -y yarn
we would need to install the dependencies in the docker container so we need to compose

2023-12-30 22:18 UTC, TheoMeunier commented on docker/php/Dockerfile
> +RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
Why removed composer ?

2023-12-30 22:18 UTC, TheoMeunier commented on docker/php/local.ini
> +memory_limit=512M
it's the memory limit of the application, do you want me to decrease it?

2026-07-12 18:41 UTC, closed without merging